project:
  type: website
  output-dir: docs

website:
  title: "Shashank Shekhar"
  site-url: https://shashankshekhar.me/
  favicon: favicon.ico
  # enhanced appearance when someone links the site
  open-graph: true
  twitter-card:
    creator: "@ShashankData"
    card-style: summary_large_image
  navbar:
    pinned: True
    left:
      - icon: house
        href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - about.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/in/shashank2806
      - icon: github
        href: https://github.com/shashank2806
      - icon: twitter
        href: https://twitter.com/ShashankData

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



